languages:
  PHP: true
engines:
  phpmd:
    enabled: true
exclude_paths:
- "tests/"
- "storage/"
- "resources/"
- "public/"
- "database/"
- "config/"
- "bootstrap/"
- "src/Infrastructure/App/Console/Commands/"

