engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- "tests/"
- "storage/"
- "resources/"
- "public/"
- "database/"
- "config/"
- "bootstrap/"
- "src/Infrastructure/App/Console/Commands/"

