engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
  scss-lint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.scss"
  - "**.js"
exclude_paths:
- "tests/"
- "storage/"
- "resources/assets/gulpfile.js"
- "resources/assets/webpack.config.js"
- "resources/lang/"
- "resources/views/"
- "public/"
- "database/"
- "config/"
- "bootstrap/"
- "src/Infrastructure/App/Console/Commands/"

