languages:
  PHP: true
engines:
  phpmd:
    enabled: true
    checks:
        Controversial/CamelCasePropertyName:
          enabled: false
        Naming/ShortVariable:
          enabled: false
exclude_paths:
- "tests/"
- "storage/"
- "resources/"
- "public/"
- "database/"
- "config/"
- "bootstrap/"
- "src/Infrastructure/App/Console/Commands/"

