language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

ratings:
  paths:
  - src/**
  - "**.php"