engines:
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
exclude_paths:
- "tests/"
- "storage/"
- "resources/"
- "public/"
- "database/"
- "config/"
- "bootstrap/"
- "src/Infrastructure/App/Console/Commands/"

