language: php

php:
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -uroot < .travis/schema.sql
  - cp .env. test .env

script:
  - mkdir -p build/logs
  - phpunit tests
